// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: departmens.sql

package postgres_sqlc

import (
	"context"
)

const addDepartment = `-- name: AddDepartment :one
INSERT INTO departments(title) 
VALUES($1)
RETURNING id
`

func (q *Queries) AddDepartment(ctx context.Context, title string) (int32, error) {
	row := q.db.QueryRow(ctx, addDepartment, title)
	var id int32
	err := row.Scan(&id)
	return id, err
}
