// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres_sqlc

type Department struct {
	ID    int32
	Title string
}

type Employee struct {
	ID           int32
	FirstName    string
	LastName     string
	DepartmentID int32
}

type Project struct {
	ID    int32
	Title string
}
