// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package postgres_sqlc

import (
	"context"
)

const addProject = `-- name: AddProject :exec
INSERT INTO projects(title) 
VALUES($1)
`

func (q *Queries) AddProject(ctx context.Context, title string) error {
	_, err := q.db.Exec(ctx, addProject, title)
	return err
}
